### ISSUE TITLE
Can't create new deco play project

### ISSUE THREAD

**Issue by felix-schindler** [deco-cx/deco#519]
On play.deco.cx the 3rd step of the manual is telling me to create a new project

> Create a new project locally
> deno run -Ar https://deco.cx/start

however, when running the command the following error occurs:

```
felix@mac ~ % deno run -Ar https://deco.cx/start
Warning Implicitly using latest version (0.209.0) for https://deno.land/std/encoding/base64.ts
error: Relative import path "std/path/mod.ts" not prefixed with / or ./ or ../
    at https://raw.githubusercontent.com/deco-cx/deco/main/engine/releases/fs.ts:2:22
```

This is because you have `"std/"` in your `import_map.json` but the way you deploy the start script, the import map isn't being used. You can easily fix this replacing the first two lines in your `engine/releases/fs.ts` with the full links of your dependencies.

https://github.com/deco-cx/deco/blob/990bc79bb8fc464328b77ccfb0de8d14eb547afc/engine/releases/fs.ts#L1

**Comment by mcandeia** [comment]
Hey @felix-schindler, sorry for the late reply, we have changed a lot since this version so I think this issue does not make sense anymore, feel free to reopen if it is the case! Thanks!
