### ISSUE TITLE
Unable to run the locally created site

### ISSUE THREAD

**Issue by akanshSirohi** [deco-cx/deco#655]
## Steps I have done to create and run new site locally
1. Cloned the repo to my file system
2. Executed the following command: 
```shell 
deno run scripts/init.ts
````
3. Followed the instructions and created new site.
4. Got into site folder and executed the command:
```shell
deno task play
```

Its showing the site available on: `https://localhost:8000` , but when I am trying to access the site, it shows me the error, I am attaching the screenshot of it. 
Note: I am using windows 11 machine.

![image](https://github.com/deco-cx/deco/assets/34837239/8bf48177-adf1-430f-942f-2e4a0092913e)

**Comment by mcandeia** [comment]
Hey @akanshSirohi a good fresh start is using our online onboarding which points out the necessary steps to get it running. Also you can start from a list of curated templates!

Try it out https://admin.deco.cx/spaces/new

Also, feel free to reopen the issue if you think still necessary!
 Thanks!
