### ISSUE TITLE
Fix typescript slow-types

### ISSUE THREAD

**Issue by mcandeia** [deco-cx/deco#790]
# Description

When publishing into JSR we are ignoring slow-types by adding `--allow-slow-types` [read more](https://jsr.io/docs/about-slow-types). Slow types should be removed in order to have better LSP.

To check where are the slow types occurrences just run `deno publish --dry-run --allow-dirty` and check the output.

**Comment by Samuel-Brito19** [comment]
I'm working on a PR for this issue.

**Comment by mcandeia** [comment]
thanks @Samuel-Brito19
